//! mod-advisor: Intelligent Ops Advisor — rule-based operational suggestions.
//!
//! Evaluates incoming events against a configurable rule engine and produces
//! actionable suggestions. Suggestions are persisted in SQLite for durability
//! across restarts.

use async_trait::async_trait;
use chrono::Utc;
use ops_pilot_sdk::context::ModuleContext;
use ops_pilot_sdk::events::OpsEvent;
use ops_pilot_sdk::traits::{HealthStatus, ModuleAction, OpsModule, ToolDefinition};
use sqlx::SqlitePool;
use tracing::info;

// ── Types ────────────────────────────────────────────────────────────────────

/// Severity level of a suggestion.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum Severity {
    Info,
    Warning,
    Critical,
}

impl std::fmt::Display for Severity {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Severity::Info => write!(f, "info"),
            Severity::Warning => write!(f, "warning"),
            Severity::Critical => write!(f, "critical"),
        }
    }
}

impl std::str::FromStr for Severity {
    type Err = anyhow::Error;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "info" => Ok(Severity::Info),
            "warning" => Ok(Severity::Warning),
            "critical" => Ok(Severity::Critical),
            _ => Err(anyhow::anyhow!("unknown severity: {}", s)),
        }
    }
}

use serde::{Deserialize, Serialize};

/// A single operational suggestion generated by the rule engine.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Suggestion {
    pub id: String,
    pub severity: Severity,
    pub category: String,
    pub title: String,
    pub description: String,
    pub suggested_action: String,
    pub source: String,
    pub created_at: String,
    pub acknowledged: bool,
    pub dismissed: bool,
}

// ── Rule Engine ──────────────────────────────────────────────────────────────

/// A rule that evaluates an event and produces suggestions.
trait Rule: Send + Sync {
    /// Human-readable name of this rule.
    fn name(&self) -> &str;

    /// Evaluate the event and return zero or more suggestions.
    fn evaluate(&self, event: &OpsEvent) -> Vec<Suggestion>;
}

/// Critical alert rule — triggers on critical-severity alerts.
struct CriticalAlertRule;

impl Rule for CriticalAlertRule {
    fn name(&self) -> &str {
        "CRITICAL_ALERT"
    }

    fn evaluate(&self, event: &OpsEvent) -> Vec<Suggestion> {
        if let OpsEvent::AlertTriggered { severity, message } = event {
            if severity == "critical" {
                return vec![make_suggestion(
                    Severity::Critical,
                    "reliability",
                    &format!("Critical alert: {}", message),
                    "A critical alert has been triggered. Immediate investigation is recommended to prevent service disruption.",
                    "Check affected services, review recent changes, and escalate if needed.",
                    self.name(),
                )];
            }
        }
        vec![]
    }
}

/// Unhealthy host rule — triggers when a host reports unhealthy status.
struct UnhealthyHostRule;

impl Rule for UnhealthyHostRule {
    fn name(&self) -> &str {
        "UNHEALTHY_HOST"
    }

    fn evaluate(&self, event: &OpsEvent) -> Vec<Suggestion> {
        if let OpsEvent::HealthCheck { host_id, status, .. } = event {
            if status == "Unhealthy" || status == "unhealthy" {
                return vec![make_suggestion(
                    Severity::Warning,
                    "reliability",
                    &format!("Host {} is unhealthy", host_id),
                    "A host has reported an unhealthy status. This may indicate connectivity issues, resource exhaustion, or service failure.",
                    "Diagnose host connectivity, check system resources (CPU, memory, disk), and verify running services.",
                    self.name(),
                )];
            }
        }
        vec![]
    }
}

/// SSH session audit rule — logs SSH session openings for audit.
struct SshSessionRule;

impl Rule for SshSessionRule {
    fn name(&self) -> &str {
        "SSH_SESSION_OPENED"
    }

    fn evaluate(&self, event: &OpsEvent) -> Vec<Suggestion> {
        if let OpsEvent::SshSessionOpened { host_id, session_id } = event {
            return vec![make_suggestion(
                Severity::Info,
                "security",
                &format!("SSH session opened to host {}", host_id),
                &format!(
                    "A new SSH session {} was established. Ensure this was an authorized access.",
                    session_id
                ),
                "Review audit logs for this session. Verify the user and purpose of the connection.",
                self.name(),
            )];
        }
        vec![]
    }
}

/// High CPU usage rule — triggers when CPU exceeds 90%.
struct HighCpuRule;

impl Rule for HighCpuRule {
    fn name(&self) -> &str {
        "METRIC_CPU_HIGH"
    }

    fn evaluate(&self, event: &OpsEvent) -> Vec<Suggestion> {
        if let OpsEvent::MetricUpdated {
            host_id, metric, value,
        } = event
        {
            if metric == "cpu" && *value > 90.0 {
                return vec![make_suggestion(
                    Severity::Warning,
                    "performance",
                    &format!("High CPU usage on host {}", host_id),
                    &format!(
                        "CPU usage has reached {:.1}%, which exceeds the 90% threshold. Sustained high CPU can degrade service performance.",
                        value
                    ),
                    "Identify top CPU-consuming processes, consider scaling horizontally or optimizing workloads.",
                    self.name(),
                )];
            }
        }
        vec![]
    }
}

/// Container restart rule — triggers on container restart events.
struct ContainerRestartRule;

impl Rule for ContainerRestartRule {
    fn name(&self) -> &str {
        "CONTAINER_RESTART"
    }

    fn evaluate(&self, event: &OpsEvent) -> Vec<Suggestion> {
        if let OpsEvent::ContainerStateChanged {
            container_id, state,
        } = event
        {
            if state == "restart" || state == "restarting" {
                return vec![make_suggestion(
                    Severity::Warning,
                    "reliability",
                    &format!("Container {} restarted", container_id),
                    "A container has restarted. Frequent restarts may indicate configuration errors, resource limits, or application crashes.",
                    "Check container logs for errors, review resource limits, and verify application health.",
                    self.name(),
                )];
            }
        }
        vec![]
    }
}

/// Audit log failure rule — triggers on failed audit outcomes.
struct AuditLogFailureRule;

impl Rule for AuditLogFailureRule {
    fn name(&self) -> &str {
        "AUDIT_LOG_FAILURE"
    }

    fn evaluate(&self, event: &OpsEvent) -> Vec<Suggestion> {
        if let OpsEvent::AuditLog {
            user, action, resource, outcome,
        } = event
        {
            if outcome == "failure" || outcome == "denied" {
                return vec![make_suggestion(
                    Severity::Info,
                    "security",
                    &format!("Audit log failure: {} on {}", action, resource),
                    &format!(
                        "User '{}' performed '{}' on '{}' with outcome '{}'. This may indicate unauthorized access attempts or misconfigurations.",
                        user, action, resource, outcome
                    ),
                    "Review user permissions, check for brute-force attempts, and verify access policies.",
                    self.name(),
                )];
            }
        }
        vec![]
    }
}

/// Helper to create a Suggestion with auto-generated id and timestamp.
fn make_suggestion(
    severity: Severity,
    category: &str,
    title: &str,
    description: &str,
    suggested_action: &str,
    source: &str,
) -> Suggestion {
    Suggestion {
        id: uuid::Uuid::new_v4().to_string(),
        severity,
        category: category.to_string(),
        title: title.to_string(),
        description: description.to_string(),
        suggested_action: suggested_action.to_string(),
        source: source.to_string(),
        created_at: Utc::now().to_rfc3339(),
        acknowledged: false,
        dismissed: false,
    }
}

// ── Module ───────────────────────────────────────────────────────────────────

/// Intelligent Ops Advisor module — evaluates events against rules and
/// produces actionable suggestions stored in SQLite.
pub struct AdvisorModule {
    db: SqlitePool,
    rules: Vec<Box<dyn Rule>>,
}

impl AdvisorModule {
    /// Create a new `AdvisorModule`, ensuring the database table exists.
    pub async fn new(db: SqlitePool) -> Self {
        sqlx::query(
            "CREATE TABLE IF NOT EXISTS advisor_suggestions (
                id TEXT PRIMARY KEY,
                severity TEXT NOT NULL,
                category TEXT NOT NULL,
                title TEXT NOT NULL,
                description TEXT NOT NULL,
                suggested_action TEXT NOT NULL,
                source TEXT NOT NULL,
                created_at TEXT NOT NULL,
                acknowledged INTEGER NOT NULL DEFAULT 0,
                dismissed INTEGER NOT NULL DEFAULT 0
            )",
        )
        .execute(&db)
        .await
        .expect("failed to create advisor_suggestions table");

        let rules: Vec<Box<dyn Rule>> = vec![
            Box::new(CriticalAlertRule),
            Box::new(UnhealthyHostRule),
            Box::new(SshSessionRule),
            Box::new(HighCpuRule),
            Box::new(ContainerRestartRule),
            Box::new(AuditLogFailureRule),
        ];

        Self { db, rules }
    }

    /// Insert a suggestion into the database.
    async fn insert_suggestion(&self, s: &Suggestion) -> anyhow::Result<()> {
        sqlx::query(
            "INSERT INTO advisor_suggestions (id, severity, category, title, description, suggested_action, source, created_at, acknowledged, dismissed) \
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        )
        .bind(&s.id)
        .bind(s.severity.to_string())
        .bind(&s.category)
        .bind(&s.title)
        .bind(&s.description)
        .bind(&s.suggested_action)
        .bind(&s.source)
        .bind(&s.created_at)
        .bind(s.acknowledged as i32)
        .bind(s.dismissed as i32)
        .execute(&self.db)
        .await?;
        Ok(())
    }

    /// List suggestions with optional filters.
    async fn list_suggestions(
        &self,
        severity: Option<&str>,
        category: Option<&str>,
        limit: u32,
    ) -> anyhow::Result<Vec<Suggestion>> {
        let mut builder: sqlx::QueryBuilder<sqlx::Sqlite> = sqlx::QueryBuilder::new(
            "SELECT id, severity, category, title, description, suggested_action, source, created_at, acknowledged, dismissed \
             FROM advisor_suggestions WHERE dismissed = 0",
        );

        if let Some(sev) = severity {
            builder.push(" AND severity = ");
            builder.push_bind(sev);
        }
        if let Some(cat) = category {
            builder.push(" AND category = ");
            builder.push_bind(cat);
        }

        builder.push(" ORDER BY created_at DESC LIMIT ");
        builder.push_bind(limit);

        let rows: Vec<DbSuggestion> = builder
            .build_query_as()
            .fetch_all(&self.db)
            .await?;

        Ok(rows.into_iter().map(DbSuggestion::into_suggestion).collect())
    }

    /// Acknowledge a suggestion.
    async fn acknowledge_suggestion(&self, id: &str) -> anyhow::Result<bool> {
        let result = sqlx::query(
            "UPDATE advisor_suggestions SET acknowledged = 1 WHERE id = ? AND acknowledged = 0",
        )
        .bind(id)
        .execute(&self.db)
        .await?;
        Ok(result.rows_affected() > 0)
    }

    /// Dismiss (soft-delete) a suggestion.
    async fn dismiss_suggestion(&self, id: &str) -> anyhow::Result<bool> {
        let result =
            sqlx::query("UPDATE advisor_suggestions SET dismissed = 1 WHERE id = ? AND dismissed = 0")
                .bind(id)
                .execute(&self.db)
                .await?;
        Ok(result.rows_affected() > 0)
    }

    /// Get aggregate statistics.
    async fn stats(&self) -> anyhow::Result<serde_json::Value> {
        #[derive(sqlx::FromRow)]
        struct SeverityCount {
            severity: String,
            count: i64,
        }

        #[derive(sqlx::FromRow)]
        struct CategoryCount {
            category: String,
            count: i64,
        }

        let total: i64 = sqlx::query_scalar(
            "SELECT COUNT(*) FROM advisor_suggestions WHERE dismissed = 0",
        )
        .fetch_one(&self.db)
        .await?;

        let by_severity: Vec<SeverityCount> = sqlx::query_as(
            "SELECT severity, COUNT(*) as count FROM advisor_suggestions WHERE dismissed = 0 GROUP BY severity",
        )
        .fetch_all(&self.db)
        .await?;

        let by_category: Vec<CategoryCount> = sqlx::query_as(
            "SELECT category, COUNT(*) as count FROM advisor_suggestions WHERE dismissed = 0 GROUP BY category",
        )
        .fetch_all(&self.db)
        .await?;

        Ok(serde_json::json!({
            "total": total,
            "by_severity": by_severity.into_iter().map(|r| serde_json::json!({
                "severity": r.severity,
                "count": r.count,
            })).collect::<Vec<_>>(),
            "by_category": by_category.into_iter().map(|r| serde_json::json!({
                "category": r.category,
                "count": r.count,
            })).collect::<Vec<_>>(),
        }))
    }

    /// Generate a health report summary.
    async fn health_report(&self) -> anyhow::Result<serde_json::Value> {
        let stats = self.stats().await?;

        let critical: i64 = sqlx::query_scalar(
            "SELECT COUNT(*) FROM advisor_suggestions WHERE severity = 'critical' AND dismissed = 0",
        )
        .fetch_one(&self.db)
        .await?;

        let unacknowledged: i64 = sqlx::query_scalar(
            "SELECT COUNT(*) FROM advisor_suggestions WHERE acknowledged = 0 AND dismissed = 0",
        )
        .fetch_one(&self.db)
        .await?;

        let overall_status = if critical > 0 {
            "degraded"
        } else if unacknowledged > 5 {
            "attention_needed"
        } else {
            "healthy"
        };

        Ok(serde_json::json!({
            "overall_status": overall_status,
            "stats": stats,
            "critical_count": critical,
            "unacknowledged_count": unacknowledged,
            "recommendation": if critical > 0 {
                "There are unaddressed critical suggestions. Immediate action recommended."
            } else if unacknowledged > 5 {
                "Multiple unacknowledged suggestions. Review and address as needed."
            } else {
                "System appears healthy. Continue monitoring."
            },
        }))
    }

    /// Evaluate an event against all rules and persist new suggestions.
    async fn evaluate_and_store(&self, event: &OpsEvent) -> anyhow::Result<Vec<Suggestion>> {
        let mut all_suggestions = Vec::new();
        for rule in &self.rules {
            let suggestions = rule.evaluate(event);
            for s in suggestions {
                self.insert_suggestion(&s).await?;
                all_suggestions.push(s);
            }
        }
        if !all_suggestions.is_empty() {
            info!(
                count = all_suggestions.len(),
                "Rule engine produced suggestions"
            );
        }
        Ok(all_suggestions)
    }
}

// ── DB row type ──────────────────────────────────────────────────────────────

#[derive(Debug, sqlx::FromRow)]
struct DbSuggestion {
    id: String,
    severity: String,
    category: String,
    title: String,
    description: String,
    suggested_action: String,
    source: String,
    created_at: String,
    acknowledged: i32,
    dismissed: i32,
}

impl DbSuggestion {
    fn into_suggestion(self) -> Suggestion {
        Suggestion {
            id: self.id,
            severity: self.severity.parse().unwrap_or(Severity::Info),
            category: self.category,
            title: self.title,
            description: self.description,
            suggested_action: self.suggested_action,
            source: self.source,
            created_at: self.created_at,
            acknowledged: self.acknowledged != 0,
            dismissed: self.dismissed != 0,
        }
    }
}

// ── OpsModule impl ───────────────────────────────────────────────────────────

#[async_trait]
impl OpsModule for AdvisorModule {
    fn name(&self) -> &str {
        "mod-advisor"
    }

    fn version(&self) -> &str {
        "0.1.0"
    }

    fn description(&self) -> &str {
        "Intelligent Ops Advisor — rule-based operational suggestions and best practice checks"
    }

    fn dependencies(&self) -> Vec<&str> {
        vec![]
    }

    fn tools(&self) -> Vec<ToolDefinition> {
        vec![
            ToolDefinition {
                name: "advisor_list".into(),
                description: "List operational suggestions with optional filters".into(),
                parameters: serde_json::json!({
                    "type": "object",
                    "properties": {
                        "severity": { "type": "string", "description": "Filter by severity: info, warning, critical" },
                        "category": { "type": "string", "description": "Filter by category: security, performance, reliability, best_practice" },
                        "limit": { "type": "integer", "description": "Max suggestions to return (default 20)", "default": 20 }
                    }
                }),
            },
            ToolDefinition {
                name: "advisor_acknowledge".into(),
                description: "Mark a suggestion as acknowledged".into(),
                parameters: serde_json::json!({
                    "type": "object",
                    "properties": {
                        "id": { "type": "string", "description": "Suggestion ID" }
                    },
                    "required": ["id"]
                }),
            },
            ToolDefinition {
                name: "advisor_dismiss".into(),
                description: "Dismiss (soft-delete) a suggestion".into(),
                parameters: serde_json::json!({
                    "type": "object",
                    "properties": {
                        "id": { "type": "string", "description": "Suggestion ID" }
                    },
                    "required": ["id"]
                }),
            },
            ToolDefinition {
                name: "advisor_stats".into(),
                description: "Get aggregate statistics of suggestions".into(),
                parameters: serde_json::json!({
                    "type": "object",
                    "properties": {}
                }),
            },
            ToolDefinition {
                name: "advisor_health_report".into(),
                description: "Generate an operational health report summary".into(),
                parameters: serde_json::json!({
                    "type": "object",
                    "properties": {}
                }),
            },
        ]
    }

    async fn execute(
        &self,
        _ctx: &ModuleContext,
        tool: &str,
        params: serde_json::Value,
    ) -> anyhow::Result<serde_json::Value> {
        match tool {
            "advisor_list" => {
                let severity = params["severity"].as_str();
                let category = params["category"].as_str();
                let limit = params["limit"].as_u64().unwrap_or(20) as u32;

                let suggestions = self.list_suggestions(severity, category, limit).await?;
                Ok(serde_json::json!({ "suggestions": suggestions }))
            }
            "advisor_acknowledge" => {
                let id = params["id"]
                    .as_str()
                    .ok_or_else(|| anyhow::anyhow!("missing 'id' parameter"))?;

                let acked = self.acknowledge_suggestion(id).await?;
                Ok(serde_json::json!({ "acknowledged": acked, "id": id }))
            }
            "advisor_dismiss" => {
                let id = params["id"]
                    .as_str()
                    .ok_or_else(|| anyhow::anyhow!("missing 'id' parameter"))?;

                let dismissed = self.dismiss_suggestion(id).await?;
                Ok(serde_json::json!({ "dismissed": dismissed, "id": id }))
            }
            "advisor_stats" => {
                let stats = self.stats().await?;
                Ok(stats)
            }
            "advisor_health_report" => {
                let report = self.health_report().await?;
                Ok(report)
            }
            _ => Err(anyhow::anyhow!("unknown tool: {}", tool)),
        }
    }

    async fn on_event(&self, _ctx: &ModuleContext, event: &OpsEvent) -> Option<ModuleAction> {
        let _suggestions = self.evaluate_and_store(event).await.ok()?;
        None
    }

    async fn health_check(&self, _ctx: &ModuleContext) -> HealthStatus {
        HealthStatus::Healthy
    }
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use ops_pilot_sdk::context::{EventBus, ModuleContext};
    use std::path::PathBuf;
    use std::sync::Arc;

    async fn setup() -> (AdvisorModule, ModuleContext) {
        let pool = SqlitePool::connect("sqlite::memory:").await.unwrap();
        let module = AdvisorModule::new(pool.clone()).await;
        let ctx = ModuleContext::new(
            Arc::new(pool),
            EventBus::new(16),
            PathBuf::from("/tmp/test-advisor"),
            "test-advisor".into(),
        );
        (module, ctx)
    }

    #[tokio::test]
    async fn test_module_metadata() {
        let (m, _ctx) = setup().await;
        assert_eq!(m.name(), "mod-advisor");
        assert_eq!(m.version(), "0.1.0");
        assert!(m.description().contains("Advisor"));
    }

    #[tokio::test]
    async fn test_tools_registered() {
        let (m, _ctx) = setup().await;
        let tools = m.tools();
        assert_eq!(tools.len(), 5);
        let names: Vec<&str> = tools.iter().map(|t| t.name.as_str()).collect();
        assert!(names.contains(&"advisor_list"));
        assert!(names.contains(&"advisor_acknowledge"));
        assert!(names.contains(&"advisor_dismiss"));
        assert!(names.contains(&"advisor_stats"));
        assert!(names.contains(&"advisor_health_report"));
    }

    #[tokio::test]
    async fn test_critical_alert_rule() {
        let (m, _ctx) = setup().await;
        let event = OpsEvent::AlertTriggered {
            severity: "critical".into(),
            message: "Disk full on prod-db".into(),
        };
        let suggestions = m.evaluate_and_store(&event).await.unwrap();
        assert_eq!(suggestions.len(), 1);
        assert_eq!(suggestions[0].severity, Severity::Critical);
        assert_eq!(suggestions[0].category, "reliability");
        assert!(suggestions[0].title.contains("Disk full"));
    }

    #[tokio::test]
    async fn test_non_critical_alert_no_suggestion() {
        let (m, _ctx) = setup().await;
        let event = OpsEvent::AlertTriggered {
            severity: "warning".into(),
            message: "CPU high".into(),
        };
        let suggestions = m.evaluate_and_store(&event).await.unwrap();
        assert!(suggestions.is_empty());
    }

    #[tokio::test]
    async fn test_unhealthy_host_rule() {
        let (m, _ctx) = setup().await;
        let event = OpsEvent::HealthCheck {
            host_id: uuid::Uuid::new_v4(),
            status: "Unhealthy".into(),
            details: serde_json::json!({}),
        };
        let suggestions = m.evaluate_and_store(&event).await.unwrap();
        assert_eq!(suggestions.len(), 1);
        assert_eq!(suggestions[0].severity, Severity::Warning);
        assert_eq!(suggestions[0].category, "reliability");
    }

    #[tokio::test]
    async fn test_ssh_session_rule() {
        let (m, _ctx) = setup().await;
        let event = OpsEvent::SshSessionOpened {
            host_id: uuid::Uuid::new_v4(),
            session_id: uuid::Uuid::new_v4(),
        };
        let suggestions = m.evaluate_and_store(&event).await.unwrap();
        assert_eq!(suggestions.len(), 1);
        assert_eq!(suggestions[0].severity, Severity::Info);
        assert_eq!(suggestions[0].category, "security");
    }

    #[tokio::test]
    async fn test_high_cpu_rule() {
        let (m, _ctx) = setup().await;
        let event = OpsEvent::MetricUpdated {
            host_id: uuid::Uuid::new_v4(),
            metric: "cpu".into(),
            value: 95.0,
        };
        let suggestions = m.evaluate_and_store(&event).await.unwrap();
        assert_eq!(suggestions.len(), 1);
        assert_eq!(suggestions[0].severity, Severity::Warning);
        assert_eq!(suggestions[0].category, "performance");
    }

    #[tokio::test]
    async fn test_cpu_below_threshold_no_suggestion() {
        let (m, _ctx) = setup().await;
        let event = OpsEvent::MetricUpdated {
            host_id: uuid::Uuid::new_v4(),
            metric: "cpu".into(),
            value: 50.0,
        };
        let suggestions = m.evaluate_and_store(&event).await.unwrap();
        assert!(suggestions.is_empty());
    }

    #[tokio::test]
    async fn test_container_restart_rule() {
        let (m, _ctx) = setup().await;
        let event = OpsEvent::ContainerStateChanged {
            container_id: "abc123".into(),
            state: "restart".into(),
        };
        let suggestions = m.evaluate_and_store(&event).await.unwrap();
        assert_eq!(suggestions.len(), 1);
        assert_eq!(suggestions[0].severity, Severity::Warning);
        assert_eq!(suggestions[0].category, "reliability");
    }

    #[tokio::test]
    async fn test_audit_failure_rule() {
        let (m, _ctx) = setup().await;
        let event = OpsEvent::AuditLog {
            user: "alice".into(),
            action: "ssh_connect".into(),
            resource: "host/prod-1".into(),
            outcome: "failure".into(),
        };
        let suggestions = m.evaluate_and_store(&event).await.unwrap();
        assert_eq!(suggestions.len(), 1);
        assert_eq!(suggestions[0].severity, Severity::Info);
        assert_eq!(suggestions[0].category, "security");
    }

    #[tokio::test]
    async fn test_list_and_dismiss() {
        let (m, ctx) = setup().await;

        // Create a suggestion via event
        let event = OpsEvent::AlertTriggered {
            severity: "critical".into(),
            message: "Test alert".into(),
        };
        let suggestions = m.evaluate_and_store(&event).await.unwrap();
        let id = &suggestions[0].id;

        // List should show it
        let result = m
            .execute(&ctx, "advisor_list", serde_json::json!({}))
            .await
            .unwrap();
        assert_eq!(result["suggestions"].as_array().unwrap().len(), 1);

        // Dismiss it
        let result = m
            .execute(
                &ctx,
                "advisor_dismiss",
                serde_json::json!({ "id": id }),
            )
            .await
            .unwrap();
        assert_eq!(result["dismissed"], true);

        // List should be empty now
        let result = m
            .execute(&ctx, "advisor_list", serde_json::json!({}))
            .await
            .unwrap();
        assert_eq!(result["suggestions"].as_array().unwrap().len(), 0);
    }

    #[tokio::test]
    async fn test_acknowledge() {
        let (m, ctx) = setup().await;

        let event = OpsEvent::HealthCheck {
            host_id: uuid::Uuid::new_v4(),
            status: "Unhealthy".into(),
            details: serde_json::json!({}),
        };
        let suggestions = m.evaluate_and_store(&event).await.unwrap();
        let id = &suggestions[0].id;

        let result = m
            .execute(
                &ctx,
                "advisor_acknowledge",
                serde_json::json!({ "id": id }),
            )
            .await
            .unwrap();
        assert_eq!(result["acknowledged"], true);
    }

    #[tokio::test]
    async fn test_stats() {
        let (m, ctx) = setup().await;

        // Create some suggestions
        m.evaluate_and_store(&OpsEvent::AlertTriggered {
            severity: "critical".into(),
            message: "Alert 1".into(),
        })
        .await
        .unwrap();
        m.evaluate_and_store(&OpsEvent::AlertTriggered {
            severity: "critical".into(),
            message: "Alert 2".into(),
        })
        .await
        .unwrap();
        m.evaluate_and_store(&OpsEvent::HealthCheck {
            host_id: uuid::Uuid::new_v4(),
            status: "Unhealthy".into(),
            details: serde_json::json!({}),
        })
        .await
        .unwrap();

        let result = m
            .execute(&ctx, "advisor_stats", serde_json::json!({}))
            .await
            .unwrap();
        assert_eq!(result["total"], 3);
    }

    #[tokio::test]
    async fn test_health_report() {
        let (m, ctx) = setup().await;

        let result = m
            .execute(&ctx, "advisor_health_report", serde_json::json!({}))
            .await
            .unwrap();
        assert_eq!(result["overall_status"], "healthy");
        assert_eq!(result["critical_count"], 0);
    }

    #[tokio::test]
    async fn test_unknown_tool() {
        let (m, ctx) = setup().await;
        let result = m.execute(&ctx, "nonexistent", serde_json::json!({})).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_severity_display_and_parse() {
        assert_eq!(Severity::Info.to_string(), "info");
        assert_eq!(Severity::Warning.to_string(), "warning");
        assert_eq!(Severity::Critical.to_string(), "critical");

        assert_eq!("info".parse::<Severity>().unwrap(), Severity::Info);
        assert_eq!("warning".parse::<Severity>().unwrap(), Severity::Warning);
        assert_eq!("critical".parse::<Severity>().unwrap(), Severity::Critical);
        assert!("unknown".parse::<Severity>().is_err());
    }

    #[tokio::test]
    async fn test_no_event_produces_no_suggestions() {
        let (m, _ctx) = setup().await;
        let event = OpsEvent::ConnectionAdded {
            id: uuid::Uuid::new_v4(),
            kind: "ssh".into(),
            name: "test".into(),
        };
        let suggestions = m.evaluate_and_store(&event).await.unwrap();
        assert!(suggestions.is_empty());
    }
}
