import '@testing-library/jest-dom';
import { vi } from 'vitest';

(globalThis as Record<string, unknown>).IS_REACT_ACT_ENVIRONMENT = true;

// Mock useI18n hook - this will be applied to all tests
vi.mock('../i18n', () => ({
  useI18n: () => ({
    t: (key: string) => {
      // Return the key itself as a fallback, or a mapped value
      const translations: Record<string, string> = {
        'chat.start': 'Start a conversation with the OpsPilot agent.',
        'chat.placeholder': 'Type a message...',
        'chat.send': 'Send',
        'chat.connecting': 'Connecting...',
        'chat.thinking': 'Thinking...',
        'chat.step': 'Step',
        'chat.login_required': 'Please login to use AI chat.',
        'chat.hint': 'Tip: Start with "diagnose:" for auto-diagnosis or "query:" for natural language queries',
        'chat.quick.diagnose': 'Diagnose',
        'chat.quick.knowledge': 'Search Knowledge',
        'chat.quick.metrics': 'Query Metrics',
        'chat.quick.hosts': 'Host Status',
        'chat.quick.alerts': 'Recent Alerts',
        'chat.prompt.diagnose': 'Please help diagnose host issue: ',
        'chat.prompt.metrics': 'Query host metrics: ',
        'chat.prompt.knowledge': 'Search knowledge base: ',
        'chat.prompt.hosts': 'List all host status',
        'chat.prompt.alerts': 'View recent alerts',
        'chat.nl_query_prefix': 'Query',
        'chat.nl_query_intent': 'Intent',
        'chat.nl_query_result': 'Result',
        'chat.diagnose_prefix': 'Diagnose',
        'chat.diagnose_report': 'Diagnosis Report',
        'chat.diagnose_issue': 'Issue',
        'chat.diagnose_severity': 'Severity',
        'chat.diagnose_causes': 'Possible Causes',
        'chat.diagnose_actions': 'Recommended Actions',
        'title.dashboard': 'Dashboard',
        'title.chat': 'Agent Chat',
        'title.modules': 'Modules',
        'title.hosts': 'Hosts',
        'title.vault': 'Vault',
        'title.security': 'Security Scanning',
        'title.health': 'Health Dashboard',
        'title.topo': 'Topology',
        'title.monitor': 'Monitor',
        'title.escalation': 'Escalation',
        'title.fim': 'File Integrity',
        'title.baseline': 'Baseline',
        'title.runbook': 'Runbook',
        'title.knowledge': 'Knowledge Base',
        'title.config': 'Configuration',
        'title.webhook': 'Webhooks',
        'title.scheduler': 'Scheduler',
        'title.filesync': 'File Sync',
        'title.advisor': 'Advisor',
        'title.terminal': 'Web Terminal',
        'title.audit': 'Audit Log',
        'title.users': 'User Management',
        'title.alert_rules': 'Alert Rules',
        'title.alert_history': 'Alert History',
        'title.channels': 'Notification Channels',
        'title.cmdb': 'Configuration Management',
        'title.timeline': 'Event Timeline',
        'title.cicd': 'CI/CD Pipelines',
        'title.metrics_viz': 'Metrics Dashboard',
        'modules.title': 'Modules',
        'modules.reload': 'Reload',
        'modules.loading': 'Loading...',
        'modules.name': 'Name',
        'modules.version': 'Version',
        'modules.description': 'Description',
        'modules.health': 'Health',
        'modules.enabled': 'Enabled',
        'modules.healthy': 'Healthy',
        'modules.degraded': 'Degraded',
        'modules.unhealthy': 'Unhealthy',
        'health.title': 'Health Dashboard',
        'health.refresh': 'Refresh',
        'health.module': 'Module',
        'health.status': 'Status',
        'health.enabled': 'Enabled',
        'host.title': 'Hosts',
        'host.reload': 'Reload',
        'host.loading': 'Loading...',
        'host.empty': 'No hosts configured',
        'host.add': 'Add Host',
        'host.name': 'Name',
        'host.address': 'Address',
        'host.port': 'Port',
        'host.status': 'Status',
        'host.actions': 'Actions',
        'host.edit': 'Edit',
        'host.delete': 'Delete',
        'host.select_host': 'Select host',
        'host.collect': 'Collect Metrics',
        'host.collecting': 'Collecting...',
        'host.hint': 'Select a host and click "Collect Metrics" to start monitoring',
        'nav.logout': 'Logout',
        'nav.back': 'Back',
        'nav.light': 'Light',
        'nav.dark': 'Dark',
        'lang.zh': '中文',
        'lang.en': 'English',
      };
      return translations[key] || key;
    },
    lang: 'en',
    setLang: vi.fn(),
  }),
}));
